"""migrate to firebase

Revision ID: ae344d827f82
Revises: da10cc52fca0
Create Date: 2026-07-31 17:49:43.188025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae344d827f82'
down_revision: Union[str, Sequence[str], None] = 'da10cc52fca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_users_firebase_uid', 'users', ['firebase_uid'])

    # 2. Now create the user_stats table
    op.create_table(
        'user_stats',
        sa.Column('total_score', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.firebase_uid']),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.drop_index(op.f('ix_stats_user_id'), table_name='stats')
    op.drop_table('stats')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'firebase_uid')
    op.create_table('stats',
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('stats_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stats_pkey'))
    )
    op.create_index(op.f('ix_stats_user_id'), 'stats', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
